export const AUTH_APP_ROUTER = 'AUTH_APP_ROUTER'
export const AUTH_DEFAULT_ROUTER = 'AUTH_DEFAULT_ROUTER'
export const AUTH_MENU_LIST = 'AUTH_MENU_LIST'
export const AUTH_USER_NICKNAME = 'AUTH_USER_NICKNAME'
export const AUTH_USER_MESSAGE = 'AUTH_USER_MESSAGE'
export const AUTH_USER_DATA = 'AUTH_USER_DATA'
export const LOGOUT = 'LOGOUT'
export const RECORD_USERINFO = 'RECORD_USERINFO'

export const RECORD_OVERVIEW_ACCESS = 'RECORD_OVERVIEW_ACCESS'; // 访问统计
export const RECORD_OVERVIEW_SERVICE = 'RECORD_OVERVIEW_SERVICE'; // 异常服务统计
export const RECORD_ACCESS_IP = 'RECORD_ACCESS_IP';
export const RECORD_USER_LOG = 'RECORD_USER_LOG';